# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer1.ord1.example.com:
  orderer1.ord2.example.com:
  peer0.org1.example.com:
  peer1.org1.example.com:
  peer2.org1.example.com:
  peer3.org1.example.com:
  peer4.org1.example.com:
  peer5.org1.example.com:
  peer6.org1.example.com:
  peer7.org1.example.com:
  peer8.org1.example.com:
  peer9.org1.example.com:
  peer10.org1.example.com:
  peer11.org1.example.com:
  peer12.org1.example.com:
  peer13.org1.example.com:
  peer14.org1.example.com:
  peer0.org2.example.com:
  peer1.org2.example.com:
  peer2.org2.example.com:
  peer3.org2.example.com:
  peer4.org2.example.com:
  peer5.org2.example.com:
  peer6.org2.example.com:
  peer7.org2.example.com:
  peer8.org2.example.com:
  peer9.org2.example.com:
  peer10.org2.example.com:
  peer11.org2.example.com:
  peer12.org2.example.com:
  peer13.org2.example.com:
  peer14.org2.example.com:


networks:
  byfn:

services:

  orderer1.ord1.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer1.ord1.example.com
    container_name: orderer1.ord1.example.com
    networks:
      - byfn

  orderer1.ord2.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer1.ord2.example.com
    container_name: orderer1.ord2.example.com
    networks:
      - byfn

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.example.com
    networks:
      - byfn

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.example.com
    networks:
      - byfn
  
  peer2.org1.example.com:
    container_name: peer2.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.org1.example.com
    networks:
      - byfn

  peer3.org1.example.com:
    container_name: peer3.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer3.org1.example.com
    networks:
      - byfn
  
  peer4.org1.example.com:
    container_name: peer4.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer4.org1.example.com
    networks:
      - byfn

  peer5.org1.example.com:
    container_name: peer5.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer5.org1.example.com
    networks:
      - byfn

  peer6.org1.example.com:
    container_name: peer6.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer6.org1.example.com
    networks:
      - byfn

  peer7.org1.example.com:
    container_name: peer7.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer7.org1.example.com
    networks:
      - byfn

  peer8.org1.example.com:
    container_name: peer8.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer8.org1.example.com
    networks:
      - byfn

  peer9.org1.example.com:
    container_name: peer9.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer9.org1.example.com
    networks:
      - byfn
  
  peer10.org1.example.com:
    container_name: peer10.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer10.org1.example.com
    networks:
      - byfn

  peer11.org1.example.com:
    container_name: peer11.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer11.org1.example.com
    networks:
      - byfn
  
  peer12.org1.example.com:
    container_name: peer12.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer12.org1.example.com
    networks:
      - byfn

  peer13.org1.example.com:
    container_name: peer13.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer13.org1.example.com
    networks:
      - byfn
  
  peer14.org1.example.com:
    container_name: peer14.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer14.org1.example.com
    networks:
      - byfn

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.example.com
    networks:
      - byfn

  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.example.com
    networks:
      - byfn

  peer2.org2.example.com:
    container_name: peer2.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.org2.example.com
    networks:
      - byfn

  peer3.org2.example.com:
    container_name: peer3.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer3.org2.example.com
    networks:
      - byfn

  peer4.org2.example.com:
    container_name: peer4.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer4.org2.example.com
    networks:
      - byfn


  peer5.org2.example.com:
    container_name: peer5.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer5.org2.example.com
    networks:
      - byfn

  peer6.org2.example.com:
    container_name: peer6.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer6.org2.example.com
    networks:
      - byfn

  peer7.org2.example.com:
    container_name: peer7.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer7.org2.example.com
    networks:
      - byfn


  peer8.org2.example.com:
    container_name: peer8.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer8.org2.example.com
    networks:
      - byfn

  peer9.org2.example.com:
    container_name: peer9.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer9.org2.example.com
    networks:
      - byfn
  
  peer10.org2.example.com:
    container_name: peer10.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer10.org2.example.com
    networks:
      - byfn

  peer11.org2.example.com:
    container_name: peer11.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer11.org2.example.com
    networks:
      - byfn

  peer12.org2.example.com:
    container_name: peer12.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer12.org2.example.com
    networks:
      - byfn

  peer13.org2.example.com:
    container_name: peer13.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer13.org2.example.com
    networks:
      - byfn

  peer14.org2.example.com:
    container_name: peer14.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer14.org2.example.com
    networks:
      - byfn


  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric-samples/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer1.ord1.example.com
      - orderer1.ord2.example.com
      - peer0.org1.example.com
      - peer1.org1.example.com
      - peer0.org2.example.com
      - peer1.org2.example.com
    networks:
      - byfn
